name: ci
run-name: ${{ github.ref }} by ${{ github.actor }}

on:
  push: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup tools
        uses: jdx/mise-action@v2
        with:
          cache: true
          install: true
      - name: Install deps
        run: bun install --frozen-lockfile      
      - name: Test
        run: bun run test
